### ISSUE TITLE
可以建一个Discord群吗?

### ISSUE THREAD

**Issue by LucasLauDev** [Huanying04/Nekobot#1]
我看到你做的机器人的功能的确很不错，但我想请教一些技术上的事情，因为我也喜欢pixiv网站上的图片，希望能开个群一起讨论聊天或者是寻求帮助。谢谢。

**Comment by Huanying04** [comment]
目前由於沒有什麼關注度，所以我也不希望創的discord群只有平常只有蚊子而已。
如果有什麼問題的話我覺得email我比較快。

**Comment by LucasLauDev** [comment]
Email 发来发去有点麻烦，而且我也没你email。。

**Comment by Huanying04** [comment]
不然email我給你我的discord帳號，就加好友，比較好討論。然後我的email不就在我的github頁面上嗎？

**Comment by eason8** [comment]
請問要怎麼打包阿(第一次做的新手)

**Comment by yorumina** [comment]
> 請問要怎麼打包阿(第一次做的新手)

我照著你講得做好了之後就不會了...

**Comment by Huanying04** [comment]
其實我也不是很清楚，我是用Intellij IDEA的這個IDE幫我弄好的
我也還只是個學生，目前還在學習當中，所以如果有不懂的地方建議上網查吧，我也給不出個好答案

**Comment by yorumina** [comment]
我也是學生欸…

**Comment by yorumina** [comment]
現在正在學
